from typing import TypedDict
from typing import List
from typing import Dict
from typing import Any


class AgentState(TypedDict, total=False):

    # User Input
    question: str

    # Router Decision
    route: str

    # RAG Documents
    documents: str

    # Final Answer
    answer: str

    # Chat Memory
    chat_history: List[str]

    # Existing Outputs
    sql_response: str
    tool_output: str

    # -------- New Multi-Agent Fields -------- #

    # Execution plan generated by Orchestrator
    execution_plan: List[str]

    # Stores outputs of all executed agents
    execution_results: Dict[str, Any]